version: '3'
services:
  master-node:
    build: master/
    tty: true
    ports:
     - "5001:22"
     - "2633:2633"
     - "9869:9869"
  worker-node:
    build: worker/
    tty: true
    ports:
     - "5002:22"